import type { CaseStudy } from "./types";

export const CASES: CaseStudy[] = [
  {
    slug: "berlin-thesis-quantum",
    title: "A thesis that finally explained itself",
    client: "PhD candidate, TU Berlin",
    country: "DE",
    countryName: "Germany",
    language: "en",
    languageName: "English",
    documentType: "thesis",
    industry: "academic",
    editingLevel: "developmental",
    wordCountBefore: 52_400,
    wordCountAfter: 41_870,
    readabilityBefore: 28,
    readabilityAfter: 47,
    turnaroundHours: 168,
    date: "2025-02-14",
    excerptBefore:
      "It is possible to argue that the observed anomalous behavior, in a manner that could potentially be considered somewhat surprising, deviates from the theoretical baseline predicted by the model which was developed in the previous chapter of this dissertation.",
    excerptAfter:
      "The observed anomaly breaks from the baseline predicted in Chapter 3. The deviation is small, but it is consistent — and it is what the rest of this thesis sets out to explain.",
    editorsNote:
      "The physics was brilliant; the sentences were hiding it. We broke long clauses, made the claims explicit, and cut 10,500 words without losing a single idea.",
    tags: ["quantum", "physics", "academic"],
    rating: 5,
  },
  {
    slug: "tokyo-product-launch-copy",
    title: "Website copy for a Tokyo fintech launch",
    client: "Kintai Labs",
    country: "JP",
    countryName: "Japan",
    language: "en",
    languageName: "English",
    documentType: "website-copy",
    industry: "finance",
    editingLevel: "line-edit",
    wordCountBefore: 4_200,
    wordCountAfter: 2_850,
    readabilityBefore: 41,
    readabilityAfter: 68,
    turnaroundHours: 48,
    date: "2025-05-02",
    excerptBefore:
      "Our comprehensive AI-driven financial infrastructure platform empowers enterprises to leverage synergistic data pipelines across multi-region deployments at global scale.",
    excerptAfter:
      "Move money across borders in seconds. One API. Seven currencies. Compliance handled.",
    editorsNote:
      "Translated-from-engineer-English into something a CFO would actually forward. We kept every product claim; we just made them land.",
    tags: ["fintech", "launch", "website"],
    rating: 5,
  },
  {
    slug: "lagos-grant-health",
    title: "A grant proposal that won ₦180M for maternal health",
    client: "Aduke Health Initiative",
    country: "NG",
    countryName: "Nigeria",
    language: "en",
    languageName: "English",
    documentType: "grant-proposal",
    industry: "ngo",
    editingLevel: "developmental",
    wordCountBefore: 18_900,
    wordCountAfter: 14_200,
    readabilityBefore: 35,
    readabilityAfter: 58,
    turnaroundHours: 120,
    date: "2024-11-08",
    excerptBefore:
      "The organization has, over the course of several years, engaged in various activities aimed at the provision of health-related services to women in underserved communities.",
    excerptAfter:
      "For six years, Aduke has delivered prenatal care to 12,400 women in the Niger Delta. This grant will let us reach 40,000 more by 2027.",
    editorsNote:
      "Numbers were buried under bureaucracy. We pulled every impact metric to the surface and rebuilt the narrative around a single promise.",
    tags: ["grant", "maternal-health", "africa"],
    rating: 5,
  },
  {
    slug: "sao-paulo-novel-debut",
    title: "A debut novel, finally brave enough",
    client: "Mariana R., novelist",
    country: "BR",
    countryName: "Brazil",
    language: "en",
    languageName: "English",
    documentType: "fiction",
    industry: "creative",
    editingLevel: "developmental",
    wordCountBefore: 98_400,
    wordCountAfter: 84_100,
    readabilityBefore: 62,
    readabilityAfter: 74,
    turnaroundHours: 336,
    date: "2024-09-21",
    excerptBefore:
      "She walked into the room and she felt something that she thought might have been sadness, or maybe it was just the feeling of being tired after a long day.",
    excerptAfter:
      "She walked into the room. The light was wrong. Everything was wrong.",
    editorsNote:
      "Mariana knew the story. She didn't yet trust the reader. We cut hedges, restored silence, and let the novel breathe.",
    tags: ["novel", "literary-fiction"],
    rating: 5,
  },
  {
    slug: "london-contract-saas",
    title: "A SaaS master agreement, half the pages",
    client: "Meridian Legal (for a London scale-up)",
    country: "GB",
    countryName: "United Kingdom",
    language: "en",
    languageName: "English",
    documentType: "legal-contract",
    industry: "legal",
    editingLevel: "copy-edit",
    wordCountBefore: 22_600,
    wordCountAfter: 11_900,
    readabilityBefore: 18,
    readabilityAfter: 42,
    turnaroundHours: 96,
    date: "2025-03-17",
    excerptBefore:
      "Notwithstanding anything to the contrary herein contained, the Parties hereto hereby acknowledge and agree that, in the event of any material breach of the provisions set forth in Clause 14.3, the non-breaching Party shall, at its sole discretion, be entitled to pursue any and all remedies available to it at law or in equity.",
    excerptAfter:
      "If either Party materially breaches Clause 14.3, the other Party may pursue any remedy available at law or in equity.",
    editorsNote:
      "Legal precision is not the same as legal fog. We kept every enforceable clause; we just stopped saying each one five times.",
    tags: ["saas", "b2b", "contract"],
    rating: 5,
  },
  {
    slug: "bogota-speech-minister",
    title: "A minister's speech, rewritten for the room",
    client: "Ministerio de Educación, Colombia",
    country: "CO",
    countryName: "Colombia",
    language: "es",
    languageName: "Spanish",
    documentType: "speech",
    industry: "government",
    editingLevel: "line-edit",
    wordCountBefore: 3_800,
    wordCountAfter: 2_400,
    readabilityBefore: 44,
    readabilityAfter: 71,
    turnaroundHours: 24,
    date: "2025-01-30",
    excerptBefore:
      "Es para mí un honor verdaderamente grande poder dirigirme el día de hoy a esta importante audiencia con el propósito de compartir algunas reflexiones acerca del sistema educativo.",
    excerptAfter:
      "Buenas tardes. Quiero hablarles, honestamente, sobre los niños que no llegaron hoy a clase.",
    editorsNote:
      "A speech is a conversation at scale. We cut throat-clearing, named the stakes, and gave the minister a first line nobody could look away from.",
    tags: ["speech", "education", "public-sector"],
    rating: 5,
  },
  {
    slug: "bangalore-whitepaper-ml",
    title: "An ML whitepaper engineers actually finished",
    client: "Kavya.ai",
    country: "IN",
    countryName: "India",
    language: "en",
    languageName: "English",
    documentType: "whitepaper",
    industry: "tech",
    editingLevel: "copy-edit",
    wordCountBefore: 11_200,
    wordCountAfter: 7_400,
    readabilityBefore: 32,
    readabilityAfter: 54,
    turnaroundHours: 72,
    date: "2024-12-12",
    excerptBefore:
      "The proposed methodology leverages a novel transformer-based architecture that is designed to provide state-of-the-art performance characteristics across a multitude of downstream tasks.",
    excerptAfter:
      "We introduce a 1.2B-parameter transformer that outperforms prior work on six benchmarks. Section 3 is the method; Section 4 is the results.",
    editorsNote:
      "Engineers don't skim because they're lazy. They skim because the paper wastes their time. We fixed that.",
    tags: ["ml", "research", "b2b"],
    rating: 5,
  },
  {
    slug: "stockholm-ux-microcopy",
    title: "Microcopy for a Stockholm banking app",
    client: "Nordvik Bank",
    country: "SE",
    countryName: "Sweden",
    language: "en",
    languageName: "English",
    documentType: "ux-copy",
    industry: "finance",
    editingLevel: "line-edit",
    wordCountBefore: 1_860,
    wordCountAfter: 1_120,
    readabilityBefore: 55,
    readabilityAfter: 82,
    turnaroundHours: 36,
    date: "2025-04-03",
    excerptBefore:
      "An error has occurred while attempting to process your requested transaction. Please review your input details and then try submitting the transaction again.",
    excerptAfter:
      "That didn't go through. Check the amount and try again.",
    editorsNote:
      "We replaced 62 error strings, kept every legal requirement, and made the app feel like it was on the customer's side.",
    tags: ["fintech", "ux-writing", "mobile"],
    rating: 5,
  },
  {
    slug: "dubai-press-release-summit",
    title: "A press release the newsroom ran verbatim",
    client: "Gulf Climate Summit",
    country: "AE",
    countryName: "United Arab Emirates",
    language: "en",
    languageName: "English",
    documentType: "press-release",
    industry: "ngo",
    editingLevel: "copy-edit",
    wordCountBefore: 1_400,
    wordCountAfter: 620,
    readabilityBefore: 38,
    readabilityAfter: 66,
    turnaroundHours: 18,
    date: "2025-03-22",
    excerptBefore:
      "In a historic and unprecedented moment for the region, stakeholders from across multiple sectors convened for the purpose of discussing and deliberating on the critical issue of climate change and its far-reaching implications.",
    excerptAfter:
      "DUBAI — Forty-two governments signed a binding agreement on Tuesday to halve regional methane emissions by 2030.",
    editorsNote:
      "The lede was buried under three paragraphs of throat-clearing. We put the news first. Reuters ran it within an hour.",
    tags: ["climate", "pr", "newsroom"],
    rating: 5,
  },
  {
    slug: "paris-screenplay-feature",
    title: "A feature screenplay, 30 pages tighter",
    client: "Atelier Bleu Productions",
    country: "FR",
    countryName: "France",
    language: "en",
    languageName: "English",
    documentType: "screenplay",
    industry: "creative",
    editingLevel: "developmental",
    wordCountBefore: 28_900,
    wordCountAfter: 21_600,
    readabilityBefore: 70,
    readabilityAfter: 80,
    turnaroundHours: 192,
    date: "2024-10-29",
    excerptBefore:
      "ÉLISE turns slowly toward the window, and as she does she begins to speak, her voice somewhat quiet but still audible, almost as if she were talking mostly to herself.",
    excerptAfter:
      "ÉLISE turns to the window.\n\nÉLISE (quiet)\nI wasn't going to tell him.",
    editorsNote:
      "Screenplays are verbs. We cut the adverbs, trusted the actors, and gave the director 30 fewer pages to shoot.",
    tags: ["screenplay", "feature", "drama"],
    rating: 5,
  },
  {
    slug: "nairobi-research-report-ag",
    title: "A research report that moved policy",
    client: "East Africa Food Systems Lab",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "research-report",
    industry: "academic",
    editingLevel: "line-edit",
    wordCountBefore: 34_200,
    wordCountAfter: 26_800,
    readabilityBefore: 30,
    readabilityAfter: 52,
    turnaroundHours: 144,
    date: "2025-02-26",
    excerptBefore:
      "Smallholder farmers have historically faced a multiplicity of interconnected and compounding challenges that have, in aggregate, contributed to suboptimal yield outcomes.",
    excerptAfter:
      "Smallholder farmers lose 34% of their potential yield each season. The three biggest causes — and what to do about them — are the subject of this report.",
    editorsNote:
      "Research earns trust with clarity, not ornamentation. We kept every footnote; we just let the findings lead.",
    tags: ["agriculture", "policy", "research"],
    rating: 5,
  },
  {
    slug: "toronto-business-report-q4",
    title: "A Q4 board report the board actually read",
    client: "Maple & Co.",
    country: "CA",
    countryName: "Canada",
    language: "en",
    languageName: "English",
    documentType: "business-report",
    industry: "finance",
    editingLevel: "copy-edit",
    wordCountBefore: 8_900,
    wordCountAfter: 5_100,
    readabilityBefore: 36,
    readabilityAfter: 64,
    turnaroundHours: 60,
    date: "2025-01-08",
    excerptBefore:
      "In terms of the overall performance of the business throughout the fourth quarter, it is possible to observe a number of trends that are worthy of further examination and consideration by the board.",
    excerptAfter:
      "Q4 revenue grew 18%. Churn dropped to 2.1%. Three decisions need the board's sign-off this quarter — they start on page 4.",
    editorsNote:
      "A board report is a decision memo in disguise. We surfaced the decisions, buried the housekeeping, and made page 4 unmissable.",
    tags: ["board", "finance", "reporting"],
    rating: 5,
  },
];
