import type { CaseStudy } from "./types";

export const CASES: CaseStudy[] = [
  {
    slug: "nairobi-birth-cert-correction",
    title: "A misspelled surname on a birth certificate, edited clean",
    client: "Wanjiru family, Nairobi",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "birth-certificate",
    industry: "civil-registration",
    editingLevel: "correction",
    wordCountBefore: 14,
    wordCountAfter: 3,
    readabilityBefore: 45,
    readabilityAfter: 100,
    turnaroundHours: 96,
    date: "2025-06-18",
    excerptBefore:
      "Surname: WANIJIRU · Given names: MARY WAMBUI · Father: JOHN WANIJIRU · Place of birth: Nairobi County Hospital",
    excerptAfter:
      "Surname: WANJIRU · Given names: MARY WAMBUI · Father: JOHN WANJIRU · Place of birth: Nairobi County Hospital",
    editorsNote:
      "A clerk had keyed the surname wrong on the printed certificate. I edited both instances on the high-resolution scan — matching the original typewriter spacing, ink colour and paper grain — so the corrected name reads identically to the original printing.",
    tags: ["name-edit", "birth-certificate", "scan-retouch"],
    rating: 5,
  },
  {
    slug: "mombasa-marriage-cert-replacement",
    title: "A faded marriage certificate, retouched pixel-by-pixel",
    client: "Abdi & Fatuma, Mombasa",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "marriage-certificate",
    industry: "civil-registration",
    editingLevel: "replacement",
    wordCountBefore: 18,
    wordCountAfter: 18,
    readabilityBefore: 40,
    readabilityAfter: 100,
    turnaroundHours: 72,
    date: "2025-04-02",
    excerptBefore:
      "Couple had a water-damaged 2017 marriage certificate — registrar details, signatures and stamp barely legible.",
    excerptAfter:
      "Retouched scan with registrar name, date, witness lines, signatures and stamp restored to crisp, original printing.",
    editorsNote:
      "Working from the water-stained original, I rebuilt the certificate digitally — recovering faded ink, straightening the registrar's signature, cleaning the margins, and restoring the stamp without touching any actual information.",
    tags: ["marriage-certificate", "scan-retouch", "faded-restoration"],
    rating: 5,
  },
  {
    slug: "kisumu-kcse-replacement",
    title: "A KCSE certificate scan with a faded grade line, cleaned up",
    client: "Brian Otieno, Kisumu",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "kcpe-kcse-certificate",
    industry: "education",
    editingLevel: "replacement",
    wordCountBefore: 22,
    wordCountAfter: 22,
    readabilityBefore: 35,
    readabilityAfter: 100,
    turnaroundHours: 48,
    date: "2025-07-22",
    excerptBefore:
      "2019 KCSE certificate scan — subjects readable, grades in the right column faded from years of folding.",
    excerptAfter:
      "Edited scan with every subject and grade crisp and legible; index number, year, and candidate name preserved exactly.",
    editorsNote:
      "The grade column had faded in storage. I edited the scan so each subject and grade reads crisply, without changing any of the actual results — just restoring what was already there to its original clarity.",
    tags: ["kcse", "grade-restoration", "scan-retouch"],
    rating: 5,
  },
  {
    slug: "eldoret-kcpe-name-correction",
    title: "A KCPE certificate with the wrong father's name, edited",
    client: "Mercy Chebet, Eldoret",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "kcpe-kcse-certificate",
    industry: "education",
    editingLevel: "correction",
    wordCountBefore: 5,
    wordCountAfter: 5,
    readabilityBefore: 60,
    readabilityAfter: 100,
    turnaroundHours: 36,
    date: "2025-03-11",
    excerptBefore:
      "Guardian name on 2014 KCPE certificate printed as 'SAMUEL KIPROP'.",
    excerptAfter:
      "Guardian name edited to 'SAMWEL KIPROP', matching the birth certificate and national ID exactly.",
    editorsNote:
      "Client's father's name is SAMWEL, not SAMUEL. I edited the guardian line on the scanned certificate to match the birth-certificate and ID records — preserving the KNEC typeface, paper texture and the print alignment of the rest of the document.",
    tags: ["kcpe", "name-edit", "guardian-line"],
    rating: 5,
  },
  {
    slug: "nairobi-passport-expedited",
    title: "A wrong date-of-birth digit on a passport bio-page, fixed same day",
    client: "Dr. Njeri, Nairobi",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "travel-document",
    industry: "immigration",
    editingLevel: "expedited",
    wordCountBefore: 9,
    wordCountAfter: 9,
    readabilityBefore: 50,
    readabilityAfter: 100,
    turnaroundHours: 6,
    date: "2025-09-14",
    excerptBefore:
      "Passport bio-page scan with date of birth printed as 23/05/1978.",
    excerptAfter:
      "Edited bio-page scan reading 23/05/1987 — MRZ line, fonts and security-print background preserved.",
    editorsNote:
      "A single keying error on a bio-page scan. I edited the date-of-birth digit and re-aligned the MRZ line so the lower OCR row stays valid — security-print background, font rendering and page shadows all preserved. Delivered the same afternoon.",
    tags: ["passport", "bio-page", "date-edit"],
    rating: 5,
  },
  {
    slug: "mombasa-emergency-travel",
    title: "An emergency travel document with a wrong DOB, edited in 24h",
    client: "Hassan family, Mombasa",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "travel-document",
    industry: "immigration",
    editingLevel: "expedited",
    wordCountBefore: 9,
    wordCountAfter: 2,
    readabilityBefore: 40,
    readabilityAfter: 100,
    turnaroundHours: 24,
    date: "2025-08-30",
    excerptBefore:
      "8-year-old's travel document scan with date of birth mis-keyed by one digit.",
    excerptAfter:
      "Edited scan with DOB matching the birth certificate exactly; all other particulars untouched.",
    editorsNote:
      "The child's date-of-birth on the travel document scan did not match the birth certificate. I edited just the date, preserving the serial number, photo placement, and issuing office stamp so the document reads identically to the original.",
    tags: ["travel-document", "date-edit", "minor"],
    rating: 5,
  },
  {
    slug: "nairobi-degree-retrieval",
    title: "A 1998 degree certificate scan, retouched for a Gulf contract",
    client: "Eng. Kamau, Nairobi",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "degree-diploma-craft",
    industry: "tertiary-education",
    editingLevel: "replacement",
    wordCountBefore: 30,
    wordCountAfter: 30,
    readabilityBefore: 30,
    readabilityAfter: 100,
    turnaroundHours: 96,
    date: "2025-05-26",
    excerptBefore:
      "Yellowed 1998 University of Nairobi degree scan — convocation date faded, seal cracked, age stains across the page.",
    excerptAfter:
      "Retouched print-ready scan — seal restored, convocation date crisp, stains removed, original wording and signatures untouched.",
    editorsNote:
      "Working only from a yellowed 1998 scan, I retouched the degree digitally — rebuilt the embossed seal, sharpened the convocation date, cleaned age-related stains, and evened the paper tone, without altering any actual text or signatures.",
    tags: ["degree", "scan-retouch", "faded-restoration"],
    rating: 5,
  },
  {
    slug: "eldoret-craft-cert-replacement",
    title: "A craft certificate scan with a faded grade, re-edited",
    client: "Peter Kiptoo, Eldoret",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "degree-diploma-craft",
    industry: "tertiary-education",
    editingLevel: "replacement",
    wordCountBefore: 16,
    wordCountAfter: 16,
    readabilityBefore: 35,
    readabilityAfter: 100,
    turnaroundHours: 48,
    date: "2025-02-08",
    excerptBefore:
      "Motor-vehicle mechanics craft certificate scan — grade column and issuing-centre line barely legible.",
    excerptAfter:
      "Edited scan with grade, index number, and issuing-centre line fully restored; candidate name and year preserved exactly.",
    editorsNote:
      "I edited the craft certificate scan so the faded grade and issuing-centre line read crisply again — without changing any actual marks. The client used the retouched scan as a clean digital copy of their original.",
    tags: ["craft-certificate", "grade-restoration", "scan-retouch"],
    rating: 5,
  },
];
