import type { CaseStudy } from "./types";

export const CASES: CaseStudy[] = [
  {
    slug: "nairobi-birth-cert-correction",
    title: "A birth certificate with a misspelled surname, fixed in 4 days",
    client: "Wanjiru family, Nairobi",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "birth-certificate",
    industry: "civil-registration",
    editingLevel: "correction",
    wordCountBefore: 14,
    wordCountAfter: 3,
    readabilityBefore: 45,
    readabilityAfter: 100,
    turnaroundHours: 96,
    date: "2025-06-18",
    excerptBefore:
      "Surname: WANIJIRU · Given names: MARY WAMBUI · Father: JOHN WANIJIRU · Place of birth: Nairobi County Hospital",
    excerptAfter:
      "Surname: WANJIRU · Given names: MARY WAMBUI · Father: JOHN WANJIRU · Place of birth: Nairobi County Hospital",
    editorsNote:
      "Clerk had keyed the surname wrong in 2003. We compiled the affidavit, witness statements, and hospital records, and walked the file through Sheria House. Corrected certificate issued in 4 working days.",
    tags: ["correction", "affidavit", "sheria-house"],
    rating: 5,
  },
  {
    slug: "mombasa-marriage-cert-replacement",
    title: "A marriage certificate lost in a 2023 flood — replaced",
    client: "Abdi & Fatuma, Mombasa",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "marriage-certificate",
    industry: "civil-registration",
    editingLevel: "replacement",
    wordCountBefore: 0,
    wordCountAfter: 1,
    readabilityBefore: 0,
    readabilityAfter: 100,
    turnaroundHours: 240,
    date: "2025-04-02",
    excerptBefore:
      "Couple needed the marriage certificate to register their firstborn. Original washed away in the 2023 floods. No scan, no photocopy.",
    excerptAfter:
      "Certified true copy retrieved from the Registrar of Marriages archive and delivered in sealed envelope, endorsed and stamped.",
    editorsNote:
      "We traced the 2017 registration book by district and entry number, filed the replacement application with a sworn loss affidavit, and picked up the certified copy in person.",
    tags: ["replacement", "loss-affidavit", "registrar-of-marriages"],
    rating: 5,
  },
  {
    slug: "kisumu-kcse-replacement",
    title: "A KCSE certificate replaced in time for university admission",
    client: "Brian Otieno, Kisumu",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "kcpe-kcse-certificate",
    industry: "education",
    editingLevel: "replacement",
    wordCountBefore: 0,
    wordCountAfter: 1,
    readabilityBefore: 0,
    readabilityAfter: 100,
    turnaroundHours: 336,
    date: "2025-07-22",
    excerptBefore:
      "2019 KCSE certificate destroyed in a house fire. Admission deadline at Kenyatta University in 3 weeks. Online KNEC portal returned 'record not found'.",
    excerptAfter:
      "Fresh KNEC-stamped replacement certificate issued with the original index number, grade slip, and verification letter. Admission confirmed.",
    editorsNote:
      "We pulled the school's exam index register, lodged the replacement with KNEC with a chief's letter and loss affidavit, and followed up weekly until the certificate was ready.",
    tags: ["knec", "kcse", "university-admission"],
    rating: 5,
  },
  {
    slug: "eldoret-kcpe-name-correction",
    title: "A KCPE certificate with the wrong father's name — corrected",
    client: "Mercy Chebet, Eldoret",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "kcpe-kcse-certificate",
    industry: "education",
    editingLevel: "correction",
    wordCountBefore: 5,
    wordCountAfter: 5,
    readabilityBefore: 60,
    readabilityAfter: 100,
    turnaroundHours: 480,
    date: "2025-03-11",
    excerptBefore:
      "Guardian name on 2014 KCPE certificate listed as 'SAMUEL KIPROP' — client's father is actually 'SAMWEL KIPROP'. College application rejected twice.",
    excerptAfter:
      "Corrected KCPE certificate issued by KNEC matching the birth certificate and national ID on record.",
    editorsNote:
      "Reconciled the birth certificate, primary school records, and national ID, filed the correction with KNEC and the Ministry of Education, and escorted the client to the KNEC offices to collect.",
    tags: ["knec", "kcpe", "name-correction"],
    rating: 5,
  },
  {
    slug: "nairobi-passport-expedited",
    title: "A passport renewed in 5 working days for an urgent conference",
    client: "Dr. Njeri, Nairobi",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "travel-document",
    industry: "immigration",
    editingLevel: "expedited",
    wordCountBefore: 21,
    wordCountAfter: 5,
    readabilityBefore: 40,
    readabilityAfter: 100,
    turnaroundHours: 120,
    date: "2025-09-14",
    excerptBefore:
      "Passport expired 3 weeks before a medical conference in Cape Town. eCitizen slot showed '6–8 weeks'. Flight booked for the 19th.",
    excerptAfter:
      "New biometric passport issued in 5 working days with the conference invitation attached as justification. Departure on schedule.",
    editorsNote:
      "We filed on eCitizen with the Department of Immigration fast-track, supplied the conference invite and return ticket, and picked up the passport at Nyayo House.",
    tags: ["passport", "ecitizen", "immigration-directorate"],
    rating: 5,
  },
  {
    slug: "mombasa-emergency-travel",
    title: "An emergency travel certificate for a minor in 48 hours",
    client: "Hassan family, Mombasa",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "travel-document",
    industry: "immigration",
    editingLevel: "expedited",
    wordCountBefore: 9,
    wordCountAfter: 2,
    readabilityBefore: 30,
    readabilityAfter: 100,
    turnaroundHours: 48,
    date: "2025-08-30",
    excerptBefore:
      "8-year-old needed to fly to Dar es Salaam for urgent surgery. Passport application submitted, pending. Hospital letter already issued.",
    excerptAfter:
      "Emergency Travel Certificate (ETC) issued the next working day, valid for single journey, accepted at both borders.",
    editorsNote:
      "Filed the ETC application at Immigration with the hospital admission letter, parental affidavits, and the child's birth certificate. Both parents were accompanied to the passport office for the interview.",
    tags: ["etc", "minor", "medical-travel"],
    rating: 5,
  },
  {
    slug: "nairobi-degree-retrieval",
    title: "A 1998 University of Nairobi degree retrieved for a Gulf contract",
    client: "Eng. Kamau, Nairobi",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "degree-diploma-craft",
    industry: "tertiary-education",
    editingLevel: "replacement",
    wordCountBefore: 0,
    wordCountAfter: 3,
    readabilityBefore: 0,
    readabilityAfter: 100,
    turnaroundHours: 504,
    date: "2025-05-26",
    excerptBefore:
      "Qatar employer required the original degree certificate, official transcript, and CUE verification. Client had only a photocopy from 1998.",
    excerptAfter:
      "Certified degree replacement, sealed transcript, and Commission for University Education verification letter delivered together, ready for MOFA authentication.",
    editorsNote:
      "Coordinated with UoN Main Campus Examinations office, paid the replacement fee, and shepherded the CUE verification. The MOFA apostille-equivalent followed a week later.",
    tags: ["uon", "cue", "mofa", "gulf-employment"],
    rating: 5,
  },
  {
    slug: "eldoret-craft-cert-replacement",
    title: "A lost craft certificate re-issued by KNEC in 2 weeks",
    client: "Peter Kiptoo, Eldoret",
    country: "KE",
    countryName: "Kenya",
    language: "en",
    languageName: "English",
    documentType: "degree-diploma-craft",
    industry: "tertiary-education",
    editingLevel: "replacement",
    wordCountBefore: 0,
    wordCountAfter: 1,
    readabilityBefore: 0,
    readabilityAfter: 100,
    turnaroundHours: 336,
    date: "2025-02-08",
    excerptBefore:
      "Motor vehicle mechanics craft certificate lost during a transfer. NITA verification stuck without the original. Contract offer on hold.",
    excerptAfter:
      "KNEC replacement craft certificate with matching index number and grade, plus NITA-compliant verification letter.",
    editorsNote:
      "Loss affidavit lodged with the chief, replacement filed at KNEC, and NITA verification letter requested in parallel so the employer received both in one envelope.",
    tags: ["knec", "nita", "craft-certificate"],
    rating: 5,
  },
];
